import Head from 'next/head';
import { ComponentProps } from './constants';
import NavigationBar from '../navbar';
import Footer from '../footer/Footer';

export const Container = ({ children }: ComponentProps) => {
  return (
    <div>
      <Head>
        <title>Page Title</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="container">
        <div className="header">
          <NavigationBar data={[]}/>
        </div>
        {children}
        <div className="footer">
          <Footer/>
        </div>
      </div>
    </div>
  );
};

export default Container;
