import Head from 'next/head';
import { ComponentProps } from './constants';

export const Container = ({ children }: ComponentProps) => {
  return (
    <div>
      <Head>
        <title>Page Title</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="container" className='bg-black text-white'>
        {children}
        </div>
      
    </div>
  );
};

export default Container;